// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserClient is an autogenerated mock type for the UserClient type
type UserClient struct {
	mock.Mock
}

type UserClient_Expecter struct {
	mock *mock.Mock
}

func (_m *UserClient) EXPECT() *UserClient_Expecter {
	return &UserClient_Expecter{mock: &_m.Mock}
}

// GetTelegramChat provides a mock function with given fields: ctx, userUUID
func (_m *UserClient) GetTelegramChat(ctx context.Context, userUUID string) (int64, error) {
	ret := _m.Called(ctx, userUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetTelegramChat")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userUUID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserClient_GetTelegramChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTelegramChat'
type UserClient_GetTelegramChat_Call struct {
	*mock.Call
}

// GetTelegramChat is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID string
func (_e *UserClient_Expecter) GetTelegramChat(ctx interface{}, userUUID interface{}) *UserClient_GetTelegramChat_Call {
	return &UserClient_GetTelegramChat_Call{Call: _e.mock.On("GetTelegramChat", ctx, userUUID)}
}

func (_c *UserClient_GetTelegramChat_Call) Run(run func(ctx context.Context, userUUID string)) *UserClient_GetTelegramChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserClient_GetTelegramChat_Call) Return(_a0 int64, _a1 error) *UserClient_GetTelegramChat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserClient_GetTelegramChat_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *UserClient_GetTelegramChat_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserClient creates a new instance of UserClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserClient {
	mock := &UserClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
