// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/pinai4/spaceship-factory/iam/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

type UserService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserService) EXPECT() *UserService_Expecter {
	return &UserService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, id
func (_m *UserService) Get(ctx context.Context, id uuid.UUID) (model.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UserService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *UserService_Expecter) Get(ctx interface{}, id interface{}) *UserService_Get_Call {
	return &UserService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *UserService_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *UserService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserService_Get_Call) Return(_a0 model.User, _a1 error) *UserService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.User, error)) *UserService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, id, userRegistrationInfo
func (_m *UserService) Register(ctx context.Context, id uuid.UUID, userRegistrationInfo model.UserRegistrationInfo) error {
	ret := _m.Called(ctx, id, userRegistrationInfo)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UserRegistrationInfo) error); ok {
		r0 = rf(ctx, id, userRegistrationInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type UserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userRegistrationInfo model.UserRegistrationInfo
func (_e *UserService_Expecter) Register(ctx interface{}, id interface{}, userRegistrationInfo interface{}) *UserService_Register_Call {
	return &UserService_Register_Call{Call: _e.mock.On("Register", ctx, id, userRegistrationInfo)}
}

func (_c *UserService_Register_Call) Run(run func(ctx context.Context, id uuid.UUID, userRegistrationInfo model.UserRegistrationInfo)) *UserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.UserRegistrationInfo))
	})
	return _c
}

func (_c *UserService_Register_Call) Return(_a0 error) *UserService_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserService_Register_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.UserRegistrationInfo) error) *UserService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
