// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AssemblyService is an autogenerated mock type for the AssemblyService type
type AssemblyService struct {
	mock.Mock
}

type AssemblyService_Expecter struct {
	mock *mock.Mock
}

func (_m *AssemblyService) EXPECT() *AssemblyService_Expecter {
	return &AssemblyService_Expecter{mock: &_m.Mock}
}

// AssembleShip provides a mock function with given fields: ctx, orderUUID, userUUID, delay
func (_m *AssemblyService) AssembleShip(ctx context.Context, orderUUID string, userUUID string, delay time.Duration) error {
	ret := _m.Called(ctx, orderUUID, userUUID, delay)

	if len(ret) == 0 {
		panic("no return value specified for AssembleShip")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, orderUUID, userUUID, delay)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AssemblyService_AssembleShip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssembleShip'
type AssemblyService_AssembleShip_Call struct {
	*mock.Call
}

// AssembleShip is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
//   - userUUID string
//   - delay time.Duration
func (_e *AssemblyService_Expecter) AssembleShip(ctx interface{}, orderUUID interface{}, userUUID interface{}, delay interface{}) *AssemblyService_AssembleShip_Call {
	return &AssemblyService_AssembleShip_Call{Call: _e.mock.On("AssembleShip", ctx, orderUUID, userUUID, delay)}
}

func (_c *AssemblyService_AssembleShip_Call) Run(run func(ctx context.Context, orderUUID string, userUUID string, delay time.Duration)) *AssemblyService_AssembleShip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *AssemblyService_AssembleShip_Call) Return(_a0 error) *AssemblyService_AssembleShip_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AssemblyService_AssembleShip_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) error) *AssemblyService_AssembleShip_Call {
	_c.Call.Return(run)
	return _c
}

// NewAssemblyService creates a new instance of AssemblyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssemblyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssemblyService {
	mock := &AssemblyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
