// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/pinai4/spaceship-factory/assembly/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// AssemblyProducer is an autogenerated mock type for the AssemblyProducer type
type AssemblyProducer struct {
	mock.Mock
}

type AssemblyProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *AssemblyProducer) EXPECT() *AssemblyProducer_Expecter {
	return &AssemblyProducer_Expecter{mock: &_m.Mock}
}

// ProduceShipAssembled provides a mock function with given fields: ctx, event
func (_m *AssemblyProducer) ProduceShipAssembled(ctx context.Context, event model.ShipAssembledEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ProduceShipAssembled")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ShipAssembledEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AssemblyProducer_ProduceShipAssembled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceShipAssembled'
type AssemblyProducer_ProduceShipAssembled_Call struct {
	*mock.Call
}

// ProduceShipAssembled is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.ShipAssembledEvent
func (_e *AssemblyProducer_Expecter) ProduceShipAssembled(ctx interface{}, event interface{}) *AssemblyProducer_ProduceShipAssembled_Call {
	return &AssemblyProducer_ProduceShipAssembled_Call{Call: _e.mock.On("ProduceShipAssembled", ctx, event)}
}

func (_c *AssemblyProducer_ProduceShipAssembled_Call) Run(run func(ctx context.Context, event model.ShipAssembledEvent)) *AssemblyProducer_ProduceShipAssembled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ShipAssembledEvent))
	})
	return _c
}

func (_c *AssemblyProducer_ProduceShipAssembled_Call) Return(_a0 error) *AssemblyProducer_ProduceShipAssembled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AssemblyProducer_ProduceShipAssembled_Call) RunAndReturn(run func(context.Context, model.ShipAssembledEvent) error) *AssemblyProducer_ProduceShipAssembled_Call {
	_c.Call.Return(run)
	return _c
}

// NewAssemblyProducer creates a new instance of AssemblyProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssemblyProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssemblyProducer {
	mock := &AssemblyProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
