// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/pinai4/spaceship-factory/iam/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

type SessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepository) EXPECT() *SessionRepository_Expecter {
	return &SessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, session, ttl
func (_m *SessionRepository) Create(ctx context.Context, session model.Session, ttl time.Duration) error {
	ret := _m.Called(ctx, session, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Session, time.Duration) error); ok {
		r0 = rf(ctx, session, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session model.Session
//   - ttl time.Duration
func (_e *SessionRepository_Expecter) Create(ctx interface{}, session interface{}, ttl interface{}) *SessionRepository_Create_Call {
	return &SessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session, ttl)}
}

func (_c *SessionRepository_Create_Call) Run(run func(ctx context.Context, session model.Session, ttl time.Duration)) *SessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Session), args[2].(time.Duration))
	})
	return _c
}

func (_c *SessionRepository_Create_Call) Return(_a0 error) *SessionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionRepository_Create_Call) RunAndReturn(run func(context.Context, model.Session, time.Duration) error) *SessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *SessionRepository) Get(ctx context.Context, id uuid.UUID) (model.Session, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Session, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Session); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *SessionRepository_Expecter) Get(ctx interface{}, id interface{}) *SessionRepository_Get_Call {
	return &SessionRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *SessionRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *SessionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *SessionRepository_Get_Call) Return(_a0 model.Session, _a1 error) *SessionRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.Session, error)) *SessionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
