// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// CancelOrderParams is parameters of CancelOrder operation.
type CancelOrderParams struct {
	// Order ID.
	OrderUUID uuid.UUID
	// User session UUID for authentication.
	XSessionUUID uuid.UUID
}

func unpackCancelOrderParams(packed middleware.Parameters) (params CancelOrderParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "X-Session-Uuid",
			In:   "header",
		}
		params.XSessionUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeCancelOrderParams(args [1]string, argsEscaped bool, r *http.Request) (params CancelOrderParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	// Decode header: X-Session-Uuid.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Session-Uuid",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.XSessionUUID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Session-Uuid",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// CreateOrderParams is parameters of CreateOrder operation.
type CreateOrderParams struct {
	// User session UUID for authentication.
	XSessionUUID uuid.UUID
}

func unpackCreateOrderParams(packed middleware.Parameters) (params CreateOrderParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-Session-Uuid",
			In:   "header",
		}
		params.XSessionUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeCreateOrderParams(args [0]string, argsEscaped bool, r *http.Request) (params CreateOrderParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-Session-Uuid.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Session-Uuid",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.XSessionUUID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Session-Uuid",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// GetOrderParams is parameters of GetOrder operation.
type GetOrderParams struct {
	// Order ID.
	OrderUUID uuid.UUID
	// User session UUID for authentication.
	XSessionUUID uuid.UUID
}

func unpackGetOrderParams(packed middleware.Parameters) (params GetOrderParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "X-Session-Uuid",
			In:   "header",
		}
		params.XSessionUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetOrderParams(args [1]string, argsEscaped bool, r *http.Request) (params GetOrderParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	// Decode header: X-Session-Uuid.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Session-Uuid",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.XSessionUUID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Session-Uuid",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// ProcessOrderPaymentParams is parameters of ProcessOrderPayment operation.
type ProcessOrderPaymentParams struct {
	// Order ID.
	OrderUUID uuid.UUID
	// User session UUID for authentication.
	XSessionUUID uuid.UUID
}

func unpackProcessOrderPaymentParams(packed middleware.Parameters) (params ProcessOrderPaymentParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "X-Session-Uuid",
			In:   "header",
		}
		params.XSessionUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeProcessOrderPaymentParams(args [1]string, argsEscaped bool, r *http.Request) (params ProcessOrderPaymentParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	// Decode header: X-Session-Uuid.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Session-Uuid",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.XSessionUUID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Session-Uuid",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}
