// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *GenericErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/bad_request_error
type BadRequestError struct {
	// HTTP error code.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val string) {
	s.Message = val
}

func (*BadRequestError) cancelOrderRes()         {}
func (*BadRequestError) createOrderRes()         {}
func (*BadRequestError) getOrderRes()            {}
func (*BadRequestError) processOrderPaymentRes() {}

// CancelOrderNoContent is response for CancelOrder operation.
type CancelOrderNoContent struct{}

func (*CancelOrderNoContent) cancelOrderRes() {}

// Ref: #/components/schemas/conflict_error
type ConflictError struct {
	// HTTP error code.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ConflictError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ConflictError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ConflictError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ConflictError) SetMessage(val string) {
	s.Message = val
}

func (*ConflictError) cancelOrderRes() {}

// Ref: #/components/schemas/create_order_request
type CreateOrderRequest struct {
	// User ID.
	UserUUID  uuid.UUID   `json:"user_uuid"`
	PartUuids []uuid.UUID `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderRequest) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderRequest) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// Ref: #/components/schemas/create_order_response
type CreateOrderResponse struct {
	// Order ID.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// Total Price.
	TotalPrice float64 `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderResponse) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() float64 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderResponse) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

func (*CreateOrderResponse) createOrderRes() {}

// Ref: #/components/schemas/generic_error
type GenericError struct {
	// HTTP error code.
	Code OptInt `json:"code"`
	// Error description.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val OptString) {
	s.Message = val
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

// Ref: #/components/schemas/internal_server_error
type InternalServerError struct {
	// HTTP error code.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*InternalServerError) cancelOrderRes()         {}
func (*InternalServerError) createOrderRes()         {}
func (*InternalServerError) getOrderRes()            {}
func (*InternalServerError) processOrderPaymentRes() {}

// Ref: #/components/schemas/not_found_error
type NotFoundError struct {
	// HTTP error code.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*NotFoundError) cancelOrderRes()         {}
func (*NotFoundError) getOrderRes()            {}
func (*NotFoundError) processOrderPaymentRes() {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptOrderPaymentMethod returns new OptOrderPaymentMethod with value set to v.
func NewOptOrderPaymentMethod(v OrderPaymentMethod) OptOrderPaymentMethod {
	return OptOrderPaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptOrderPaymentMethod is optional OrderPaymentMethod.
type OptOrderPaymentMethod struct {
	Value OrderPaymentMethod
	Set   bool
}

// IsSet returns true if OptOrderPaymentMethod was set.
func (o OptOrderPaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptOrderPaymentMethod) Reset() {
	var v OrderPaymentMethod
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptOrderPaymentMethod) SetTo(v OrderPaymentMethod) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptOrderPaymentMethod) Get() (v OrderPaymentMethod, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptOrderPaymentMethod) Or(d OrderPaymentMethod) OrderPaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/order
type Order struct {
	// Order ID.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// User ID.
	UserUUID  uuid.UUID   `json:"user_uuid"`
	PartUuids []uuid.UUID `json:"part_uuids"`
	// Total Price.
	TotalPrice float64 `json:"total_price"`
	// Transaction ID.
	TransactionUUID OptUUID `json:"transaction_uuid"`
	// Payment Method.
	PaymentMethod OptOrderPaymentMethod `json:"payment_method"`
	// Status.
	Status OrderStatus `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *Order) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *Order) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *Order) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *Order) GetTotalPrice() float64 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *Order) GetTransactionUUID() OptUUID {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *Order) GetPaymentMethod() OptOrderPaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *Order) GetStatus() OrderStatus {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *Order) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *Order) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *Order) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *Order) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *Order) SetTransactionUUID(val OptUUID) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *Order) SetPaymentMethod(val OptOrderPaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *Order) SetStatus(val OrderStatus) {
	s.Status = val
}

func (*Order) getOrderRes() {}

// Payment Method.
type OrderPaymentMethod string

const (
	OrderPaymentMethodUNKNOWN       OrderPaymentMethod = "UNKNOWN"
	OrderPaymentMethodCARD          OrderPaymentMethod = "CARD"
	OrderPaymentMethodSBP           OrderPaymentMethod = "SBP"
	OrderPaymentMethodCREDITCARD    OrderPaymentMethod = "CREDIT_CARD"
	OrderPaymentMethodINVESTORMONEY OrderPaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all OrderPaymentMethod values.
func (OrderPaymentMethod) AllValues() []OrderPaymentMethod {
	return []OrderPaymentMethod{
		OrderPaymentMethodUNKNOWN,
		OrderPaymentMethodCARD,
		OrderPaymentMethodSBP,
		OrderPaymentMethodCREDITCARD,
		OrderPaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderPaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case OrderPaymentMethodUNKNOWN:
		return []byte(s), nil
	case OrderPaymentMethodCARD:
		return []byte(s), nil
	case OrderPaymentMethodSBP:
		return []byte(s), nil
	case OrderPaymentMethodCREDITCARD:
		return []byte(s), nil
	case OrderPaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderPaymentMethod) UnmarshalText(data []byte) error {
	switch OrderPaymentMethod(data) {
	case OrderPaymentMethodUNKNOWN:
		*s = OrderPaymentMethodUNKNOWN
		return nil
	case OrderPaymentMethodCARD:
		*s = OrderPaymentMethodCARD
		return nil
	case OrderPaymentMethodSBP:
		*s = OrderPaymentMethodSBP
		return nil
	case OrderPaymentMethodCREDITCARD:
		*s = OrderPaymentMethodCREDITCARD
		return nil
	case OrderPaymentMethodINVESTORMONEY:
		*s = OrderPaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Status.
type OrderStatus string

const (
	OrderStatusPENDINGPAYMENT OrderStatus = "PENDING_PAYMENT"
	OrderStatusPAID           OrderStatus = "PAID"
	OrderStatusCANCELLED      OrderStatus = "CANCELLED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusPENDINGPAYMENT,
		OrderStatusPAID,
		OrderStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusPENDINGPAYMENT:
		return []byte(s), nil
	case OrderStatusPAID:
		return []byte(s), nil
	case OrderStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusPENDINGPAYMENT:
		*s = OrderStatusPENDINGPAYMENT
		return nil
	case OrderStatusPAID:
		*s = OrderStatusPAID
		return nil
	case OrderStatusCANCELLED:
		*s = OrderStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/process_order_payment_request
type ProcessOrderPaymentRequest struct {
	// Payment Method.
	PaymentMethod ProcessOrderPaymentRequestPaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *ProcessOrderPaymentRequest) GetPaymentMethod() ProcessOrderPaymentRequestPaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *ProcessOrderPaymentRequest) SetPaymentMethod(val ProcessOrderPaymentRequestPaymentMethod) {
	s.PaymentMethod = val
}

// Payment Method.
type ProcessOrderPaymentRequestPaymentMethod string

const (
	ProcessOrderPaymentRequestPaymentMethodUNKNOWN       ProcessOrderPaymentRequestPaymentMethod = "UNKNOWN"
	ProcessOrderPaymentRequestPaymentMethodCARD          ProcessOrderPaymentRequestPaymentMethod = "CARD"
	ProcessOrderPaymentRequestPaymentMethodSBP           ProcessOrderPaymentRequestPaymentMethod = "SBP"
	ProcessOrderPaymentRequestPaymentMethodCREDITCARD    ProcessOrderPaymentRequestPaymentMethod = "CREDIT_CARD"
	ProcessOrderPaymentRequestPaymentMethodINVESTORMONEY ProcessOrderPaymentRequestPaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all ProcessOrderPaymentRequestPaymentMethod values.
func (ProcessOrderPaymentRequestPaymentMethod) AllValues() []ProcessOrderPaymentRequestPaymentMethod {
	return []ProcessOrderPaymentRequestPaymentMethod{
		ProcessOrderPaymentRequestPaymentMethodUNKNOWN,
		ProcessOrderPaymentRequestPaymentMethodCARD,
		ProcessOrderPaymentRequestPaymentMethodSBP,
		ProcessOrderPaymentRequestPaymentMethodCREDITCARD,
		ProcessOrderPaymentRequestPaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ProcessOrderPaymentRequestPaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case ProcessOrderPaymentRequestPaymentMethodUNKNOWN:
		return []byte(s), nil
	case ProcessOrderPaymentRequestPaymentMethodCARD:
		return []byte(s), nil
	case ProcessOrderPaymentRequestPaymentMethodSBP:
		return []byte(s), nil
	case ProcessOrderPaymentRequestPaymentMethodCREDITCARD:
		return []byte(s), nil
	case ProcessOrderPaymentRequestPaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ProcessOrderPaymentRequestPaymentMethod) UnmarshalText(data []byte) error {
	switch ProcessOrderPaymentRequestPaymentMethod(data) {
	case ProcessOrderPaymentRequestPaymentMethodUNKNOWN:
		*s = ProcessOrderPaymentRequestPaymentMethodUNKNOWN
		return nil
	case ProcessOrderPaymentRequestPaymentMethodCARD:
		*s = ProcessOrderPaymentRequestPaymentMethodCARD
		return nil
	case ProcessOrderPaymentRequestPaymentMethodSBP:
		*s = ProcessOrderPaymentRequestPaymentMethodSBP
		return nil
	case ProcessOrderPaymentRequestPaymentMethodCREDITCARD:
		*s = ProcessOrderPaymentRequestPaymentMethodCREDITCARD
		return nil
	case ProcessOrderPaymentRequestPaymentMethodINVESTORMONEY:
		*s = ProcessOrderPaymentRequestPaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/process_order_payment_response
type ProcessOrderPaymentResponse struct {
	// Transaction ID.
	TransactionUUID uuid.UUID `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *ProcessOrderPaymentResponse) GetTransactionUUID() uuid.UUID {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *ProcessOrderPaymentResponse) SetTransactionUUID(val uuid.UUID) {
	s.TransactionUUID = val
}

func (*ProcessOrderPaymentResponse) processOrderPaymentRes() {}
