// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/pinai4/spaceship-factory/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderProducer is an autogenerated mock type for the OrderProducer type
type OrderProducer struct {
	mock.Mock
}

type OrderProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderProducer) EXPECT() *OrderProducer_Expecter {
	return &OrderProducer_Expecter{mock: &_m.Mock}
}

// ProduceOrderPaid provides a mock function with given fields: ctx, event
func (_m *OrderProducer) ProduceOrderPaid(ctx context.Context, event model.OrderPaidEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ProduceOrderPaid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderPaidEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderProducer_ProduceOrderPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceOrderPaid'
type OrderProducer_ProduceOrderPaid_Call struct {
	*mock.Call
}

// ProduceOrderPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.OrderPaidEvent
func (_e *OrderProducer_Expecter) ProduceOrderPaid(ctx interface{}, event interface{}) *OrderProducer_ProduceOrderPaid_Call {
	return &OrderProducer_ProduceOrderPaid_Call{Call: _e.mock.On("ProduceOrderPaid", ctx, event)}
}

func (_c *OrderProducer_ProduceOrderPaid_Call) Run(run func(ctx context.Context, event model.OrderPaidEvent)) *OrderProducer_ProduceOrderPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderPaidEvent))
	})
	return _c
}

func (_c *OrderProducer_ProduceOrderPaid_Call) Return(_a0 error) *OrderProducer_ProduceOrderPaid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderProducer_ProduceOrderPaid_Call) RunAndReturn(run func(context.Context, model.OrderPaidEvent) error) *OrderProducer_ProduceOrderPaid_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderProducer creates a new instance of OrderProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderProducer {
	mock := &OrderProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
