// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/pinai4/spaceship-factory/order/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, orderUUID
func (_m *OrderService) Cancel(ctx context.Context, orderUUID uuid.UUID) error {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type OrderService_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *OrderService_Expecter) Cancel(ctx interface{}, orderUUID interface{}) *OrderService_Cancel_Call {
	return &OrderService_Cancel_Call{Call: _e.mock.On("Cancel", ctx, orderUUID)}
}

func (_c *OrderService_Cancel_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *OrderService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrderService_Cancel_Call) Return(_a0 error) *OrderService_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_Cancel_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *OrderService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, orderUUID, createOrder
func (_m *OrderService) Create(ctx context.Context, orderUUID uuid.UUID, createOrder model.CreateOrder) (float64, error) {
	ret := _m.Called(ctx, orderUUID, createOrder)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.CreateOrder) (float64, error)); ok {
		return rf(ctx, orderUUID, createOrder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.CreateOrder) float64); ok {
		r0 = rf(ctx, orderUUID, createOrder)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.CreateOrder) error); ok {
		r1 = rf(ctx, orderUUID, createOrder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
//   - createOrder model.CreateOrder
func (_e *OrderService_Expecter) Create(ctx interface{}, orderUUID interface{}, createOrder interface{}) *OrderService_Create_Call {
	return &OrderService_Create_Call{Call: _e.mock.On("Create", ctx, orderUUID, createOrder)}
}

func (_c *OrderService_Create_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID, createOrder model.CreateOrder)) *OrderService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.CreateOrder))
	})
	return _c
}

func (_c *OrderService_Create_Call) Return(_a0 float64, _a1 error) *OrderService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.CreateOrder) (float64, error)) *OrderService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, orderUUID
func (_m *OrderService) Get(ctx context.Context, orderUUID uuid.UUID) (model.Order, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Order, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Order); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrderService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *OrderService_Expecter) Get(ctx interface{}, orderUUID interface{}) *OrderService_Get_Call {
	return &OrderService_Get_Call{Call: _e.mock.On("Get", ctx, orderUUID)}
}

func (_c *OrderService_Get_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *OrderService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrderService_Get_Call) Return(_a0 model.Order, _a1 error) *OrderService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.Order, error)) *OrderService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessPayment provides a mock function with given fields: ctx, orderUUID, paymentMethod
func (_m *OrderService) ProcessPayment(ctx context.Context, orderUUID uuid.UUID, paymentMethod model.OrderPaymentMethod) (uuid.UUID, error) {
	ret := _m.Called(ctx, orderUUID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPayment")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.OrderPaymentMethod) (uuid.UUID, error)); ok {
		return rf(ctx, orderUUID, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.OrderPaymentMethod) uuid.UUID); ok {
		r0 = rf(ctx, orderUUID, paymentMethod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.OrderPaymentMethod) error); ok {
		r1 = rf(ctx, orderUUID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_ProcessPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessPayment'
type OrderService_ProcessPayment_Call struct {
	*mock.Call
}

// ProcessPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
//   - paymentMethod model.OrderPaymentMethod
func (_e *OrderService_Expecter) ProcessPayment(ctx interface{}, orderUUID interface{}, paymentMethod interface{}) *OrderService_ProcessPayment_Call {
	return &OrderService_ProcessPayment_Call{Call: _e.mock.On("ProcessPayment", ctx, orderUUID, paymentMethod)}
}

func (_c *OrderService_ProcessPayment_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID, paymentMethod model.OrderPaymentMethod)) *OrderService_ProcessPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.OrderPaymentMethod))
	})
	return _c
}

func (_c *OrderService_ProcessPayment_Call) Return(_a0 uuid.UUID, _a1 error) *OrderService_ProcessPayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_ProcessPayment_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.OrderPaymentMethod) (uuid.UUID, error)) *OrderService_ProcessPayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
